module.exports = {
    aai: require("./aai"),
    batch: require("./batch"),
    billing: require("./billing"),
    bm: require("./bm"),
    cbs: require("./cbs"),
    cdb: require("./cdb"),
    cis: require("./cis"),
    common: require("./common"),
    cr: require("./cr"),
    cvm: require("./cvm"),
    cws: require("./cws"),
    dc: require("./dc"),
    dcdb: require("./dcdb"),
    ds: require("./ds"),
    dts: require("./dts"),
    iot: require("./iot"),
    iotcloud: require("./iotcloud"),
    mariadb: require("./mariadb"),
    ms: require("./ms"),
    msp: require("./msp"),
    partners: require("./partners"),
    postgres: require("./postgres"),
    scf: require("./scf"),
    soe: require("./soe"),
    sqlserver: require("./sqlserver"),
    tbaas: require("./tbaas"),
    tbm: require("./tbm"),
    tia: require("./tia"),
    tmt: require("./tmt"),
    vpc: require("./vpc"),
    youmall: require("./youmall"),
    yunjing: require("./yunjing")
};

