module.exports = {
    aai: require("./aai"),
    batch: require("./batch"),
    bm: require("./bm"),
    cbs: require("./cbs"),
    cdb: require("./cdb"),
    cis: require("./cis"),
    common: require("./common"),
    cr: require("./cr"),
    cvm: require("./cvm"),
    cws: require("./cws"),
    dc: require("./dc"),
    dcdb: require("./dcdb"),
    ds: require("./ds"),
    dts: require("./dts"),
    iot: require("./iot"),
    mariadb: require("./mariadb"),
    ms: require("./ms"),
    msp: require("./msp"),
    partners: require("./partners"),
    postgres: require("./postgres"),
    scf: require("./scf"),
    tbm: require("./tbm"),
    tia: require("./tia"),
    tmt: require("./tmt"),
    vpc: require("./vpc"),
    youmall: require("./youmall")
};

